#!/usr/bin/env python
import optparse
import sys
import csv
from collections import defaultdict

optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--threshold", dest="threshold", default=0.5, type="float", help="Threshold for aligning with Dice's coefficient (default=0.5)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=100000000000, type="int", help="Number of sentences to use for training and alignment")
optparser.add_option('-c', "--combination-type", dest='comp', default='intersection')
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

# sys.stderr.write("Training with Dice's coefficient...")
bitext = [[sentence.strip().split() for sentence in pair] for pair in zip(open(f_data), open(e_data))][:opts.num_sents]

with open('./trained/f_max.csv', mode='r', encoding='latin-1') as ffile:
  with open('./trained/e_max.csv', mode='r', encoding='latin-1') as efile:
    freader = csv.reader(ffile, delimiter='|')
    ereader = csv.reader(efile, delimiter='|')
    f_max = {rows[0]:rows[1] for rows in freader}
    e_max = {rows[0]:rows[1] for rows in ereader}


for (f, e) in bitext:
  for (i, f_i) in enumerate(f): 
    for (j, e_j) in enumerate(e):
      if (opts.comp == 'union'):
        if e_j == e_max.get(f_i, '') or f_i == f_max.get(e_j, ''):
          sys.stdout.write("%i-%i " % (i,j))
      else:
        if e_j == e_max.get(f_i, '') and f_i == f_max.get(e_j, ''):
          sys.stdout.write("%i-%i " % (i,j))
  sys.stdout.write("\n")
